addons:
  apt:
    packages:
      - python-numpy
      - python-qt4
      - python-virtualenv
      - cmake      
      - libhdf5-dev
      - libboost-python-dev
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    
language: python

notifications:
  email: false
  
python:
  - 2.7

# Use the Ubuntu Trusty travis beta because it has a better CMake
sudo: required
dist: trusty

virtualenv:
  system_site_packages: true

install:
  - pip install h5py
  - pip install -r requirements.txt

script:
  - python setup.py fetch_vigra build_vigra
  - python setup.py fetch_ilastik install_ilastik
  