addons:
  apt:
    packages:
      - python-numpy
      - python-qt4
      - python-h5py
      - cmake
      
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    
language: python

notifications:
  email: false
  
python:
  - 2.7

sudo: false

virtualenv:
  system_site_packages: true

script:
  - python setup.py build