addons:
  apt:
    packages:
      - cmake      
      - cython
      - libhdf5-dev
      - libboost-python-dev
      - libfftw3-dev
      - python-qt4
      - python-requests
      - python-setuptools
      - python-virtualenv
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    
language: python

notifications:
  email: false
  
python:
  - 2.7

# Use the Ubuntu Trusty travis beta because it has a better CMake
sudo: required
dist: trusty

virtualenv:
  system_site_packages: true

install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install numpy
  - pip install h5py

script:
  - python setup.py build install
  